-
  name: Deploy a web application
  become: true
  hosts: db_and_web_server1,db_and_web_server2
  tasks:
    - name: Install dependencies
      apt:
        name: [ 'python-setuptools', 'python-all-dev', 'build-essential', 'python-pip', 'python3-mysql.connector' ]
        state: present
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml